// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4ddS-j_Tl7U7Qknk1G6tYxOqwc5RuIk',
    appId: '1:388376482522:web:386e5a56defbb557abcbe3',
    messagingSenderId: '388376482522',
    projectId: 'fir-flutter-4eda4',
    authDomain: 'fir-flutter-4eda4.firebaseapp.com',
    storageBucket: 'fir-flutter-4eda4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0suUxxhTduQrq3ULw99-g3qH7FOxJMU',
    appId: '1:388376482522:android:98a6634a060446a5abcbe3',
    messagingSenderId: '388376482522',
    projectId: 'fir-flutter-4eda4',
    storageBucket: 'fir-flutter-4eda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRI8fch0QhwS91cKexMjJa0jD4wzBu914',
    appId: '1:388376482522:ios:4e13b892f3c59c31abcbe3',
    messagingSenderId: '388376482522',
    projectId: 'fir-flutter-4eda4',
    storageBucket: 'fir-flutter-4eda4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRI8fch0QhwS91cKexMjJa0jD4wzBu914',
    appId: '1:388376482522:ios:4e13b892f3c59c31abcbe3',
    messagingSenderId: '388376482522',
    projectId: 'fir-flutter-4eda4',
    storageBucket: 'fir-flutter-4eda4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4ddS-j_Tl7U7Qknk1G6tYxOqwc5RuIk',
    appId: '1:388376482522:web:e64a65e06d09703eabcbe3',
    messagingSenderId: '388376482522',
    projectId: 'fir-flutter-4eda4',
    authDomain: 'fir-flutter-4eda4.firebaseapp.com',
    storageBucket: 'fir-flutter-4eda4.firebasestorage.app',
  );
}
